steps_phase1: 7500
steps_phase2: 7500
steps_probe: 7500
num_workers: 0
ckpt_dir: "ckpts/" # relative path within hydra output dir
eval_batch_size: 512
device: "mps"

vae:
  lr: 0.002
  batch_size: 256
  weight_decay: 0.0
  gradient_clip:
    enabled: false
    max_norm: 10.0
    norm_type: 2.0

contrastive:
  lr: 0.001
  batch_size: 256
  weight_decay: 0.0
  gradient_clip:
    enabled: false
    max_norm: 10.0
    norm_type: 2.0

dynamics:
  lr: 0.001
  batch_size: 256
  weight_decay: 0.0
  gradient_clip:
    enabled: false
    max_norm: 10.0
    norm_type: 2.0

probe:
  lr: 0.001
  batch_size: 256
  weight_decay: 0.0
  gradient_clip:
    enabled: false
    max_norm: 10.0
    norm_type: 2.0
