defaults:
  - data: base
  - model/vae: base
  - model/contrastive: base
  - model/dynamics: base
  - model/probe: base
  - train: base
  - wandb: base
  - _self_

method: "vae" # "vae" or "contrastive"

model:
  repr: ${oc.select:model.${method}}
